#!/usr/bin/env bash
# run_index.sh — orchestrator for the analyze-repo agent's index system.
#
# Usage:
#   bash agents/scripts/run_index.sh <REPO_PATH> [FORCE_REBUILD]
#
# FORCE_REBUILD=1 wipes .analysis/indexes/ and rebuilds everything.
# FORCE_REBUILD=0 (default) rehashes, detects changes, and only rebuilds
# the affected pieces.
#
# This script performs ONLY deterministic work — hashing, diffing, grepping,
# manifest building. It does NOT generate folder summaries; those are an LLM
# step and the agent runs them itself using summarize_folder.prompt.md.

set -euo pipefail

REPO_PATH="${1:?usage: run_index.sh <REPO_PATH> [FORCE_REBUILD]}"
FORCE_REBUILD="${2:-0}"

if [[ ! -d "$REPO_PATH/.git" ]]; then
  echo "error: $REPO_PATH is not a git repo" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INDEX_DIR="$REPO_PATH/.analysis/indexes"
mkdir -p "$INDEX_DIR/folder-summaries"

# Make sure .analysis is gitignored inside the fork.
GITIGNORE="$REPO_PATH/.gitignore"
if [[ -f "$GITIGNORE" ]] && ! grep -qxF '.analysis/' "$GITIGNORE"; then
  echo '.analysis/' >> "$GITIGNORE"
  echo "note: added .analysis/ to $GITIGNORE" >&2
fi

if [[ "$FORCE_REBUILD" == "1" ]]; then
  echo "==> full rebuild (FORCE_REBUILD=1)"
  rm -f "$INDEX_DIR/manifest.json" \
        "$INDEX_DIR/symbol-map.tsv" \
        "$INDEX_DIR/file-hashes.json" \
        "$INDEX_DIR/stale-paths.txt"
fi

echo "==> hashing tracked files"
python3 "$SCRIPT_DIR/hash_tree.py" "$REPO_PATH"

echo "==> detecting changes"
python3 "$SCRIPT_DIR/detect_changes.py" "$REPO_PATH"

STALE_COUNT=0
if [[ -f "$INDEX_DIR/stale-paths.txt" ]]; then
  STALE_COUNT=$(wc -l < "$INDEX_DIR/stale-paths.txt" | tr -d ' ')
fi
echo "==> $STALE_COUNT stale paths"

if [[ "$FORCE_REBUILD" == "1" ]] || [[ ! -f "$INDEX_DIR/manifest.json" ]]; then
  echo "==> building manifest"
  python3 "$SCRIPT_DIR/build_manifest.py" "$REPO_PATH"
fi

if [[ "$FORCE_REBUILD" == "1" ]] || [[ ! -f "$INDEX_DIR/symbol-map.tsv" ]] || [[ "$STALE_COUNT" -gt 0 ]]; then
  echo "==> building symbol map"
  bash "$SCRIPT_DIR/build_symbol_map.sh" "$REPO_PATH"
fi

# Write TOC last — reflects current state of everything above.
echo "==> writing TOC.md"
TOC="$INDEX_DIR/TOC.md"
{
  echo "# Repository analysis index — $(basename "$REPO_PATH")"
  echo
  echo "_Auto-generated by \`run_index.sh\` on $(date -u +'%Y-%m-%d %H:%M:%S UTC')._"
  echo
  echo "| File | Purpose |"
  echo "| --- | --- |"
  echo "| [manifest.json](manifest.json) | Top-level directory inventory — file counts, sizes, language breakdown. |"
  echo "| [key-files.md](key-files.md) | Curated entrypoints. Hand-seeded. |"
  echo "| [symbol-map.tsv](symbol-map.tsv) | Symbol → file:line, for Ruby classes/modules and JS/TS top-level exports. |"
  echo "| [file-hashes.json](file-hashes.json) | SHA1 per tracked file — change detection source. |"
  echo "| [stale-paths.txt](stale-paths.txt) | Paths whose hash changed since last run. |"
  echo "| [folder-summaries/](folder-summaries/) | ≤ 400-word summaries per top-level folder. Generated by LLM. |"
  echo "| [last-run-stats.json](last-run-stats.json) | Token usage and file reads from the most recent analysis pass. |"
  echo
  echo "Stale paths on this run: **$STALE_COUNT**"
} > "$TOC"

echo "==> done. indexes at $INDEX_DIR"
